Fix template syntax error in operator.yaml Helm chart
This PR fixes a Go template syntax error in the operator.yaml file of the Knative Operator Helm chart. The error causes YAML parsing failures when the chart is used as a subchart in other Helm charts.

### Issue

The error occurs because the `and` function in Go templates requires two or more arguments, but it's being used with only one argument in several places in the template, such as:

```yaml
{{- if and .Values.knative_operator.operator_webhook.annotations }}
```

This is invalid Go template syntax and results in the following error when attempting to install the chart as a subchart:

Error: INSTALLATION FAILED: YAML parse error on knative/charts/knative-operator/templates/operator.yaml: error converting YAML to JSON: yaml: line 40: did not find expected key

### Changes

This PR modifies the operator.yaml template to replace all instances of single-argument `and` with direct variable access:

- Replace `{{- if and .Values.knative_operator... }}` with `{{- if .Values.knative_operator... }}`

This maintains the same logical behavior (checking if the value exists/is true) while fixing the syntax error.

Specific changes:
- Modified `{{- if and .Values.knative_operator.operator_webhook.annotations }}` to use correct syntax
- Modified `{{- if and .Values.knative_operator.operator_webhook.podAnnotations }}` to use correct syntax
- Modified `{{- if and .Values.knative_operator.operator_webhook.securityContext }}` to use correct syntax
- Modified `{{- if and .Values.knative_operator.knative_operator.annotations }}` to use correct syntax
- Modified `{{- if and .Values.knative_operator.knative_operator.podAnnotations }}` to use correct syntax
- Modified `{{- if and .Values.knative_operator.knative_operator.securityContext }}` to use correct syntax

### Testing Done

Verified that with this change:
1. The chart can be installed directly without errors
2. The chart can be used as a subchart without errors
3. All functionality remains the same (verified pods start correctly and configuration is applied properly)

### Additional Context

This issue is most noticeable when the chart is used as a dependency in another chart, as shown in this example:

```yaml
# Parent Chart.yaml
apiVersion: v2
name: knative
dependencies:
  - name: knative-operator
    version: 1.17.0
    repository: https://knative.github.io/operator
```

With values structured like:

```yaml
# Parent values.yaml
knative-operator:
  knative_operator:
    knative_operator:
      image: gcr.io/knative-releases/knative.dev/operator/cmd/operator
      tag: v1.17.4
    operator_webhook:
      image: gcr.io/knative-releases/knative.dev/operator/cmd/webhook
      tag: v1.17.4
    kubernetes_min_version: v1.25.0
```
```